(()=>{if(window.__perfilMuro)return;window.__perfilMuro=1;
const $=i=>document.getElementById(i),N=(i,d=0)=>{let v=parseFloat($(i)?.value);return Number.isFinite(v)?v:d},F=(v,d=2)=>Number(v).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
let st=document.createElement('style');st.textContent=`.mfbrand{max-width:1180px;margin:0 auto 12px}.mfbrand img{width:220px;max-width:55vw}.tabs{display:flex;gap:8px;margin:0 0 16px}.tab{background:#e9eef5;color:#17202a;border:1px solid #cbd5e1}.tab.on{background:#1f6feb;color:white}.pane{display:none}.pane.on{display:block}.pc{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.ps{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:14px 0}.tw{overflow:auto}.tw th,.tw td{white-space:nowrap}.crit{background:#fff7ed}#profileSvg{width:100%;height:auto;border:1px solid #d0d7de;border-radius:10px;background:#fff}@media(max-width:850px){.pc,.ps{grid-template-columns:1fr}}`;document.head.append(st);
let h=document.querySelector('header');if(h&&!document.querySelector('.mfbrand')){let d=document.createElement('div');d.className='mfbrand';d.innerHTML='<img src="manfredini-logo.png" alt="Manfredini Engenharia">';h.prepend(d)}
let main=document.querySelector('main'),old=[...main.children],tabs=document.createElement('div'),calc=document.createElement('div'),prof=document.createElement('div');tabs.className='tabs';tabs.innerHTML='<button type="button" class="tab on" data-p="c">Calculadora estrutural</button><button type="button" class="tab" data-p="p">Perfil do muro</button>';calc.className='pane on';prof.className='pane';old.forEach(x=>calc.appendChild(x));main.append(tabs,calc,prof);
prof.innerHTML=`<section class="card full"><h2>Perfil do muro – cargas por pilar</h2><div class="pc"><div><label>Comprimento total (m)</label><input id="pL" type="number" step=".01" value="37.12"></div><div><label>Trecho inicial H constante (m)</label><input id="pF" type="number" step=".01" value="20"></div><div><label>Altura inicial H₀ (m)</label><input id="pH" type="number" step=".01" value="3.50"></div><div><label>Trechos de redução (m)</label><input id="pS" type="number" step=".1" value="5"></div><div><label>Redução sugerida/trecho (m)</label><input id="pD" type="number" step=".05" value=".50"><small>Valor inicial editável, não é dado medido do terreno.</small></div><div><label>Espaçamento máximo pilares (m)</label><input id="pE" type="number" step=".01" value="2"></div></div><div class="note">Primeiros 20 m a 3,50 m. Depois, informe a queda de altura em cada trecho de 5 m. O programa distribui os pilares uniformemente sem ultrapassar o espaçamento máximo.</div><div class="actions"><button class="primary" type="button" id="pGen">Atualizar perfil</button><button class="secondary" type="button" id="pCSV">Baixar CSV para CYPECAD</button></div></section>
<section class="card full"><h2>Reduções após o trecho inicial</h2><div class="tw"><table><thead><tr><th>Trecho</th><th>Início</th><th>Fim</th><th>Redução (m)</th><th>H final</th></tr></thead><tbody id="pDrops"></tbody></table></div></section>
<section class="card full"><h2>Desenho longitudinal</h2><svg id="profileSvg" viewBox="0 0 1120 430"></svg></section>
<section class="card full"><h2>Pilares P1, P2, P3... – cargas para CYPECAD</h2><div class="ps"><div class="result"><div class="k">Pilares</div><div class="v" id="pNP">–</div></div><div class="result"><div class="k">Espaçamento real</div><div class="v" id="pER">–</div></div><div class="result"><div class="k">Pilares a 3,50 m</div><div class="v" id="pNF">–</div></div><div class="result"><div class="k">Maior momento</div><div class="v" id="pMM">–</div></div></div><div class="tw"><table><thead><tr><th>Pilar</th><th>x (m)</th><th>H (m)</th><th>Faixa trib. (m)</th><th>w topo</th><th>w base solo+q</th><th>água base</th><th>H total (kN)</th><th>M base (kN·m)</th></tr></thead><tbody id="pRows"></tbody></table></div><div class="note">Extremos usam meia faixa tributária; pilares internos usam a faixa inteira. São usados γ, φ, c, q, Ka e nível d’água da aba principal. Valores são de pré-dimensionamento.</div></section>`;
tabs.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{tabs.querySelectorAll('.tab').forEach(x=>x.classList.toggle('on',x===b));calc.classList.toggle('on',b.dataset.p==='c');prof.classList.toggle('on',b.dataset.p==='p');if(b.dataset.p==='p')run()});
let drops=[],last=[];function segs(){let L=Math.max(.1,N('pL',37.12)),f=Math.max(0,Math.min(L,N('pF',20))),s=Math.max(.1,N('pS',5)),a=[];for(let x=f;x<L-1e-8&&a.length<50;){let e=Math.min(L,x+s);a.push([x,e]);x=e}return a}
function build(keep=true){let old=keep?[...drops]:[],d=Math.max(0,N('pD',.5)),a=segs();drops=a.map((_,i)=>Number.isFinite(old[i])?old[i]:d);$('pDrops').innerHTML=a.map((z,i)=>`<tr><td>T${i+1}</td><td>${F(z[0])}</td><td>${F(z[1])}</td><td><input class="pd" data-i="${i}" type="number" min="0" step=".05" value="${drops[i].toFixed(2)}"></td><td id="ph${i}">–</td></tr>`).join('');document.querySelectorAll('.pd').forEach(x=>x.oninput=()=>{drops[+x.dataset.i]=Math.max(0,+x.value||0);run()});run()}
function pts(){let L=Math.max(.1,N('pL',37.12)),f=Math.max(0,Math.min(L,N('pF',20))),h=Math.max(0,N('pH',3.5)),a=[{x:0,h}],sg=segs();if(f)a.push({x:f,h});sg.forEach((z,i)=>{h=Math.max(0,h-(drops[i]||0));a.push({x:z[1],h});let c=$('ph'+i);if(c)c.textContent=F(h)});return a}
function hat(x,p){for(let i=1;i<p.length;i++){let a=p[i-1],b=p[i];if(x<=b.x+1e-9)return b.x===a.x?b.h:a.h+(b.h-a.h)*(x-a.x)/(b.x-a.x)}return p.at(-1).h}
function run(){let L=Math.max(.1,N('pL',37.12)),H0=Math.max(0,N('pH',3.5)),em=Math.max(.2,N('pE',2)),nv=Math.max(1,Math.ceil(L/em-1e-10)),e=L/nv,p=pts(),gam=N('gamma',19),phi=N('phi',28),q=N('q',9.81),c=N('coesao',0),ka0=Math.pow(Math.tan(Math.PI/4-phi*Math.PI/360),2),Ka=$('kamode')?.value==='manual'?N('kaman',ka0):ka0,Hw0=Math.max(0,N('Hw',0)),pt=Math.max(0,Ka*q-2*c*Math.sqrt(Ka)),rows=[],mm=0,nf=0;for(let i=0;i<=nv;i++){let x=i*e,H=hat(x,p),tr=(i===0||i===nv)?e/2:e,pb=Math.max(0,Ka*(q+gam*H)-2*c*Math.sqrt(Ka)),wt=pt*tr,wb=pb*tr,R=(wt+wb)*H/2,M=wt*H*H/2+(wb-wt)*H*H/6,Hw=Math.min(H,Hw0),ww=9.81*Hw*tr,Rw=ww*Hw/2,Mw=Rw*Hw/3,Rt=R+Rw,Mt=M+Mw;if(Math.abs(H-H0)<.005)nf++;mm=Math.max(mm,Mt);rows.push({p:'P'+(i+1),x,H,tr,wt,wb,ww,Rt,Mt})}last=rows;$('pNP').textContent=rows.length;$('pER').textContent=F(e,3)+' m';$('pNF').textContent=nf;$('pMM').textContent=F(mm)+' kN·m';$('pRows').innerHTML=rows.map(r=>`<tr class="${Math.abs(r.H-H0)<.005?'crit':''}"><td><b>${r.p}</b></td><td>${F(r.x,3)}</td><td>${F(r.H,3)}</td><td>${F(r.tr,3)}</td><td>${F(r.wt)}</td><td>${F(r.wb)}</td><td>${F(r.ww)}</td><td><b>${F(r.Rt)}</b></td><td><b>${F(r.Mt)}</b></td></tr>`).join('');draw(p,rows,L,H0)}
function draw(p,r,L,H0){let s=$('profileSvg'),W=1120,H=430,m={l:55,r:25,t:35,b:75},by=H-m.b,mh=Math.max(H0,...p.map(z=>z.h),.5),X=x=>m.l+x/L*(W-m.l-m.r),Y=h=>by-h/mh*(by-m.t),poly=[`${X(0)},${by}`,...p.map(z=>`${X(z.x)},${Y(z.h)}`),`${X(L)},${by}`].join(' '),line=p.map(z=>`${X(z.x)},${Y(z.h)}`).join(' ');let a=`<rect width="${W}" height="${H}" fill="#fff"/><line x1="${m.l}" y1="${by}" x2="${W-m.r}" y2="${by}" stroke="#475569" stroke-width="2"/><polygon points="${poly}" fill="#c68642" opacity=".3"/><polyline points="${line}" fill="none" stroke="#9a5b2a" stroke-width="4"/>`;r.forEach((z,i)=>{let x=X(z.x),y=Y(z.H);a+=`<line x1="${x}" y1="${by}" x2="${x}" y2="${y}" stroke="#2563eb" stroke-width="${Math.abs(z.H-H0)<.005?2.5:1.5}"/><circle cx="${x}" cy="${y}" r="3" fill="#1d4ed8"/><text x="${x}" y="${by+18+(i%2)*15}" text-anchor="middle" font-size="10">${z.p}</text>`});p.forEach(z=>a+=`<text x="${X(z.x)}" y="${Y(z.h)-7}" text-anchor="middle" font-size="12" font-weight="700" fill="#7c2d12">${F(z.h)} m</text>`);a+=`<text x="${m.l}" y="22" font-size="14" font-weight="700">Perfil longitudinal – ${F(L)} m</text>`;s.innerHTML=a}
function csv(){if(!last.length)run();let h=['Pilar','x (m)','H (m)','Faixa tributaria (m)','w topo (kN/m)','w base solo+q (kN/m)','agua base (kN/m)','H total (kN)','M base (kN.m)'],l=[h.join(';'),...last.map(r=>[r.p,r.x,r.H,r.tr,r.wt,r.wb,r.ww,r.Rt,r.Mt].map((v,i)=>i?String(v).replace('.',','):v).join(';'))],b=new Blob(['\ufeff'+l.join('\n')],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='perfil_muro_cargas_cypecad.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
$('pGen').onclick=()=>build(false);$('pCSV').onclick=csv;['pL','pF','pH','pS','pD','pE'].forEach(i=>$(i).oninput=()=>['pL','pF','pS'].includes(i)?build(true):run());['gamma','phi','q','coesao','kaman','kamode','Hw'].forEach(i=>$(i)?.addEventListener('input',run));build(false);
})();